apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-backend
  labels:
     app : nginx_backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx_backend
  template:
    metadata:
      labels:
        app: nginx_backend
    spec:
      containers:
      - name: myimage
        image: puneet2022/learning:myimage
        ports:
        - containerPort: 80
